config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require "domain"
  devise_for :users
  mount StripeEvent::Engine, at: "/stripe-webhooks"
  get "/", to: "pages#home"

  post "/webhooks/:source", to: "webhooks#create"

  require "sidekiq/web"
  require "sidekiq-scheduler/web"
  authenticate :user, -> (user) { user.queen? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  resources :filterables, only: [], param: :model_name do
    resource :filters, only: %i[show create], controller: "filterable/filters"
    resources :views, only: %i[create], controller: "filterable/views"
    collection do
      resources :views, only: %i[destroy], as: :filterable_view, controller: "filterable/views"
    end
  end

  get "/admin", to: "admin/items#index"

  devise_scope :user do
    namespace :queen do
      authenticate :user, -> (user) { user.queen? } do
        resources :users, only: %i[index show edit update destroy new create] do
          patch :set_localhost, on: :member
        end
        resources :store_orders, only: %i[index show]
        resources :events, only: [:index, :show] do
          post :relaunch, on: :member
        end
      end
    end

    resource :profile, only: %i[edit update]

    namespace :admin do
      authenticate :user, -> (user) { user.queen? || user.admin? } do
        resource :instagram, only: [:show, :update] do
          patch :update_engagement_config, on: :member
          post :launch_engagement, on: :member
          patch :toggle_status, on: :member
        end
        get "instagram/logs", to: "instagram_logs#index", as: :instagram_logs
        resources :authors do
          delete :remove_avatar, on: :member, controller: :avatars
        end
        resource :onboarding, only: %i[new create]
        resource :subscription, only: %i[create destroy]
        resources :stores, only: %i[show edit update] do
          resources :categories, only: %i[new create edit update]
          resources :shipping_methods, only: %i[new create edit update]
          resources :specifications, only: %i[new create edit update]
        end
        resources :specifications, only: [:destroy, :index, :new, :create, :edit, :update]
        resources :categories, only: [:destroy, :index, :new, :create, :edit, :update]
        resources :shipping_methods, only: [:destroy]
        resources :collections, only: %i[index new create edit destroy update]
        resources :carousel_cards, only: %i[new create edit destroy update] do
          patch :update_position, on: :member
        end
        resource :bulk_edit_items, only: [] do
          patch :online, on: :member
          patch :offline, on: :member
          patch :add_to_collection, on: :member
        end

        resources :items, only: %i[index new create edit update destroy] do
          delete :remove_photo, on: :member, controller: :photos
          patch :archive, on: :member, controller: :archives
          patch :unarchive, on: :member, controller: :archives
          patch :add_stock, on: :member, controller: :stocks
          patch :remove_stock, on: :member, controller: :stocks
        end

        resources :orders, only: %i[index show destroy]
        resources :bookings, only: %i[index new create show edit update destroy] do
          post :add_step, on: :member
          post :reset_steps, on: :member
          post :create_message, on: :member
          post :fetch_instagram_messages, on: :member
        end
        resources :venues
        resources :booking_contacts
        resource :account, only: %i[show edit update]
      end
    end
  end

  constraints(Domain) do
    root to: "pages#home"
    get "/contact",         to: "pages#contact"
    get "/about",           to: "pages#about"
    post "/send_message",   to: "pages#send_message"
    get "/store",           to: "stores#show"
    get "/library",         to: "stores#library"
    get "/portfolio",       to: "pages#portfolio"
    get "/authors", to: "ttt/authors#index"
    get "/authors/:id", to: "ttt/authors#show", as: :author
    get "/confidentiality", to: "pages#confidentiality"

    resource :checkout, only: [:show] do
      post :confirm_payment, ons: :member
    end
    resources :items, only: [:show] do
      resource :checkout, only: [] do
        post :add, on: :member, controller: :carts
        post :remove, on: :member, controller: :carts
      end
    end
    resources :orders, only: [:show]
    resources :order_intents, only: [:create]
    resource :order_intents, only: [] do
      patch :undo_shipping_method, on: :member
      patch :undo_service_point, on: :member
      patch :shipping_method, on: :member
      patch :service_point, on: :member
    end
  end

  namespace :api do
    resources :social_campagnes, only: [] do
      member do
        get :status
        patch :status
        post :logs
      end
      resources :social_targets, only: [] do
        member do
          post :like
          patch :update
        end
      end
    end
  end
end

app/views/chalky/common/_navbar.html.slim
/ - color = home?(params) ? "text-light" : "text-contrast"
/ .fixed.top-2.right-6.z-50.text-contrast = render "shared/cart"

/ .w-full.hidden.md:flex.bg-light.relative.cursor-default.items-center.flex-col.border-b.boder-light
/   .justify-end.px-24.items-center.w-full.transition.absolute.top-0.py-8.z-40.flex.gap-8
/     .absolute.left-12
/       - unless home?(params)
/         = link_to root_path do
/           = image_tag("#{Current.store.slug}/logo_black.png", class: "h-16")
/     = link_to "À propos", about_path, class: "btn-link font-anemone font-normal tracking-wider #{color}"
/     = link_to "Contact", contact_path, class: "btn-link  font-anemone font-normal tracking-wider #{color}"
/     = link_to "Boutique", store_path, class: "btn-link  font-anemone font-normal tracking-wider #{color}"

/ .md:hidden

/   = label_tag :phonenav, class: "fixed shadow-xl z-40 top-4 left-4 rounded-full" do
/     .w-16.h-16.bg-secondary.flex.items-center.justify-center.rounded-full.p-3
/       <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
/         <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
/       </svg>
/   = check_box_tag :phonenav, nil, nil, {class: "hidden peer"}
/   .z-50.fixed.hidden.peer-checked:block.top-0.left-0.right-0.bottom-0.bg-secondary/90
/     = label_tag :phonenav, class: "absolute top-10 right-10" do
/       .w-16.h-16.flex.items-center.justify-center.rounded-full.p-3.text-light
/         <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12">
/           <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
/         </svg>
/     .flex.flex-col.justify-around.items-start.py-12.px-12
/       = link_to "À propos", about_path, class: "tracking-widest text-5xl text-light mb-8"
/       = link_to "Contact", contact_path, class: "tracking-widest text-5xl text-light mb-8"
/       = link_to "Boutique", store_path, class: "tracking-widest text-5xl text-light mb-8"