config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require "domain"
  devise_for :users
  mount StripeEvent::Engine, at: "/stripe-webhooks"
  get "/", to: "pages#home"

  post "/webhooks/:source", to: "webhooks#create"

  require "sidekiq/web"
  require "sidekiq-scheduler/web"
  authenticate :user, -> (user) { user.queen? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  resources :filterables, only: [], param: :model_name do
    resource :filters, only: %i[show create], controller: "filterable/filters"
    resources :views, only: %i[create], controller: "filterable/views"
    collection do
      resources :views, only: %i[destroy], as: :filterable_view, controller: "filterable/views"
    end
  end

  get "/admin", to: "admin/items#index"

  devise_scope :user do
    namespace :queen do
      authenticate :user, -> (user) { user.queen? } do
        resources :users, only: %i[index show edit update destroy new create] do
          patch :set_localhost, on: :member
        end
        resources :store_orders, only: %i[index show]
        resources :events, only: [:index, :show] do
          post :relaunch, on: :member
        end
      end
    end

    resource :profile, only: %i[edit update]

    namespace :admin do
      authenticate :user, -> (user) { user.queen? || user.admin? } do
        resource :instagram, only: [:show, :update] do
          patch :update_engagement_config, on: :member
          post :launch_engagement, on: :member
          patch :toggle_status, on: :member
        end
        get "instagram/logs", to: "instagram_logs#index", as: :instagram_logs
        resources :authors do
          delete :remove_avatar, on: :member, controller: :avatars
        end
        resource :onboarding, only: %i[new create]
        resource :subscription, only: %i[create destroy]
        resources :stores, only: %i[show edit update] do
          resources :categories, only: %i[new create edit update]
          resources :shipping_methods, only: %i[new create edit update]
          resources :specifications, only: %i[new create edit update]
        end
        resources :specifications, only: [:destroy, :index, :new, :create, :edit, :update]
        resources :categories, only: [:destroy, :index, :new, :create, :edit, :update]
        resources :shipping_methods, only: [:destroy]
        resources :collections, only: %i[index new create edit destroy update]
        resources :carousel_cards, only: %i[new create edit destroy update] do
          patch :update_position, on: :member
        end
        resource :bulk_edit_items, only: [] do
          patch :online, on: :member
          patch :offline, on: :member
          patch :add_to_collection, on: :member
        end

        resources :items, only: %i[index new create edit update destroy] do
          delete :remove_photo, on: :member, controller: :photos
          patch :archive, on: :member, controller: :archives
          patch :unarchive, on: :member, controller: :archives
          patch :add_stock, on: :member, controller: :stocks
          patch :remove_stock, on: :member, controller: :stocks
        end

        resources :orders, only: %i[index show destroy]
        resources :bookings, only: %i[index new create show edit update destroy] do
          post :add_step, on: :member
          post :reset_steps, on: :member
          post :create_message, on: :member
          post :fetch_instagram_messages, on: :member
        end
        resources :venues
        resources :booking_contacts
        resource :account, only: %i[show edit update]
      end
    end
  end

  constraints(Domain) do
    root to: "pages#home"
    get "/contact",         to: "pages#contact"
    get "/about",           to: "pages#about"
    post "/send_message",   to: "pages#send_message"
    get "/store",           to: "stores#show"
    get "/library",         to: "stores#library"
    get "/portfolio",       to: "pages#portfolio"
    get "/authors", to: "ttt/authors#index"
    get "/authors/:id", to: "ttt/authors#show", as: :author
    get "/confidentiality", to: "pages#confidentiality"

    resource :checkout, only: [:show] do
      post :confirm_payment, ons: :member
    end
    resources :items, only: [:show] do
      resource :checkout, only: [] do
        post :add, on: :member, controller: :carts
        post :remove, on: :member, controller: :carts
      end
    end
    resources :orders, only: [:show]
    resources :order_intents, only: [:create]
    resource :order_intents, only: [] do
      patch :undo_shipping_method, on: :member
      patch :undo_service_point, on: :member
      patch :shipping_method, on: :member
      patch :service_point, on: :member
    end
  end

  namespace :api do
    resources :social_campagnes, only: [] do
      member do
        get :status
        patch :status
        post :logs
      end
      resources :social_targets, only: [] do
        member do
          post :like
          patch :update
        end
      end
    end
  end
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  extend Enumerize
  include PgSearch::Model

  enumerize :status, in: %i[pending processed failed], default: :pending

  pg_search_scope :search_by_source_and_data,
                  against: [:source, :data, :processing_errors],
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/controllers/queen/events_controller.rb
module Queen
  class EventsController < QueenController
    def index
      if params[:search].present?
        search_events
        respond_to { |format| format.turbo_stream }
      else
        @events = Event.order(created_at: :desc)
        @pagy, @events = pagy(@events)
      end
    end

    def show
      @event = Event.find(params[:id])
    end

    def relaunch
      @event = Event.find(params[:id])
      EventJob.perform_later(@event)

      respond_to do |format|
        format.html { redirect_to queen_events_path, notice: "L'event a été relancé avec succès" }
        format.turbo_stream
      end
    end

    private

    def search_events
      @events = Event.search_by_source_and_data(params[:search])
      @pagy, @events = pagy(@events)
    end
  end
end

app/controllers/queen/store_orders_controller.rb
# frozen_string_literal: true

module Queen
  class StoreOrdersController < QueenController
    def index
      @store_orders = StoreOrder.all
    end

    def show; end
  end
end

app/controllers/queen/users_controller.rb
# frozen_string_literal: true

module Queen
  class UsersController < QueenController
    def index
      @users = User.all
    end

    def new
      @user = User.new
      @user.build_store
    end

    def edit
      @user = User.find(params[:id])
    end

    def create
      @user = User.new(user_params)
      @user.password = Devise.friendly_token.first(8)
      @user.store.admin = @user
      @user.store.stripe_subscription_id = "DEV____#{SecureRandom.uuid}"

      if @user.save
        redirect_to queen_users_path, status: :see_other, notice: t(".success")
      else
        render :new, status: :unprocessable_entity, notice: t(".error")
      end
    end

    def update
      @user = User.find(params[:id])

      if @user.update(user_params)
        redirect_to queen_users_path, status: :see_other, notice: t(".success")
      else
        render :edit, status: :unprocessable_entity, notice: t(".error")
      end
    end

    def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect_to queen_users_path, status: :see_other, notice: t(".success")
    end

    def set_localhost
      @user = User.find(params[:id])
      Store.update_all(domain: nil)
      @user.store.update(domain: "localhost")
      redirect_to queen_users_path, status: :see_other, notice: t(".success")
    end

    private

    def user_params
      params.require(:user).permit(
        :first_name,
        :last_name,
        :email,
        :phone,
        :role,
        store_attributes: [
          :id,
          :name,
          :address,
          :city,
          :postal_code,
          :country,
          :domain,
          :slug,
          :about,
          :mail_body,
          :holiday,
          :holiday_sentence,
          :display_stock,
          :meta_title,
          :meta_description,
          :meta_image,
          :instagram_url,
          :facebook_url,
          :postmark_key,
          :sendcloud_private_key,
          :sendcloud_public_key,
          :rates,
          :stripe_account_id,
          :charges_enable,
          :payouts_enable,
          :details_submitted,
          :stripe_subscription_id,
          :subscription_status,
          :stripe_checkout_session_id
        ]
      )
    end
  end
end

app/controllers/queen_controller.rb
# frozen_string_literal: true

class QueenController < ApplicationController
  before_action :authenticate_user!
  layout "queen"
end

app/helpers/events_helper.rb
module EventsHelper
  def status_color(status)
    case status
    when "pending"
      "bg-yellow-100 text-yellow-800"
    when "processed"
      "bg-green-100 text-green-800"
    when "failed"
      "bg-red-100 text-red-800"
    else
      "bg-gray-100 text-gray-800"
    end
  end
end

app/views/queen/events/_events_table.html.slim
.table.w-full.pb-36.mt-6
  .table-header-group
    .table-row
      .table-cell.text-sm.font-semibold.text-contrast
        | ID
      .table-cell.text-sm.font-semibold.text-contrast
        | Source
      .table-cell.text-sm.font-semibold.text-contrast
        | Status
      .table-cell.text-sm.font-semibold.text-contrast
        | Erreurs
      .table-cell.text-sm.font-semibold.text-contrast
        | Créé le
      .table-cell.w-8.text-right
        span.sr-only
          | Actions

  .table-row-group
    - events.each do |event|
      .table-row.hover:bg-gray-50
        .table-cell.whitespace-nowrap.py-4.pl-4.pr-3.text-sm.sm:pl-6
          = event.id
        .table-cell.whitespace-nowrap.px-3.py-4.text-sm.text-gray-500
          = event.source
        .table-cell.whitespace-nowrap.px-3.py-4.text-sm
          .inline-flex.items-center.rounded-md.px-2.py-1 class=status_color(event.status)
            = event.status
        .table-cell.whitespace-nowrap.px-3.py-4.text-sm.text-gray-500
          = truncate(event.processing_errors, length: 50) if event.processing_errors.present?
        .table-cell.whitespace-nowrap.px-3.py-4.text-sm.text-gray-500
          = l(event.created_at, format: :short)
        .table-cell.relative.whitespace-nowrap.py-4.pl-3.pr-4.text-right.text-sm.font-medium.sm:pr-6
          .flex.items-center.justify-end.gap-2
            = link_to queen_event_path(event), class: "text-indigo-600 hover:text-indigo-900" do
              i.fas.fa-eye.mr-2
              | Voir
            = button_to relaunch_queen_event_path(event), class: "text-indigo-600 hover:text-indigo-900", data: { turbo_confirm: "Êtes-vous sûr de vouloir relancer cet event ?" } do
              i.fas.fa-redo.mr-2
              | Relancer

app/views/queen/events/index.html.slim
= render Header::Component.new do |header|
  - header.with_tabs do
    = render Tabs::Component.new(tabs: [{name: "Events", path: queen_events_path}])

  .px-4.sm:px-6.lg:px-0
    .sm:flex.sm:items-center.mb-6
      .sm:flex-auto
        h1.text-base.font-semibold.leading-6.text-contrast
          | Events
        p.mt-2.text-sm.text-midgray
          | Liste de tous les événements du système.

    .mt-8.flow-root
      .flex.w-full.gap-3
        = form_tag queen_events_path, method: :get, data: { turbo_stream: true, controller: :autosave }, class: "w-full" do
          .flex.items-center
            = text_field_tag :search, params[:search], class: "form-input w-full placeholder:text-content z-30", placeholder: "Rechercher un event", data: { action: "keyup->autosave#submit"}

      .-mx-4.-my-2.overflow-x-auto.sm:-mx-6.lg:-mx-8
        .inline-block.min-w-full.py-2.align-middle.sm:px-6.lg:px-8
          #events-table
            = render partial: "events_table", locals: { events: @events }

    - header.with_pagination do
      == pagy_nav(@pagy)

app/views/queen/events/index.turbo_stream.slim
= turbo_stream.update "events-table" do
  = render partial: "events_table", locals: { events: @events }

app/views/queen/events/relaunch.turbo_stream.slim
= turbo_stream.prepend "notifications" do
  = render(Notifications::Component.new(type: "success", data: {title: "Event relancé", body: "L'event a été relancé avec succès"}))

app/views/queen/events/show.html.slim
= render Header::Component.new do |header|
  - header.with_tabs do
    = render Tabs::Component.new(tabs: [{name: "Events", path: queen_events_path}])
  - header.with_action_link do
    = link_to queen_events_path do
      = render Buttons::Option::Component.new(label: "Retour aux events", icon: "fa-solid fa-arrow-left")

  .px-4.sm:px-6.lg:px-0
    .sm:flex.sm:items-center.mb-6
      .sm:flex-auto
        h1.text-base.font-semibold.leading-6.text-contrast
          | Event ##{@event.id}

    .mt-8.flow-root
      .bg-white.shadow.sm:rounded-lg
        .px-4.py-5.sm:p-6
          .space-y-6
            .flex.items-center.justify-between
              .text-sm.font-medium.text-gray-500 Source
              .text-sm.text-gray-900 = @event.source

            .flex.items-center.justify-between
              .text-sm.font-medium.text-gray-500 Status
              .inline-flex.items-center.rounded-md.px-2.py-1 class=status_color(@event.status)
                = @event.status

            .flex.items-center.justify-between
              .text-sm.font-medium.text-gray-500 Créé le
              .text-sm.text-gray-900 = l(@event.created_at, format: :long)

            - if @event.processing_errors.present?
              .border-t.border-gray-200.pt-4
                .text-sm.font-medium.text-gray-500.mb-2 Erreurs de traitement
                div.bg-gray-50.p-4.rounded-lg.text-sm.text-red-600.overflow-auto.max-h-96
                  = @event.processing_errors

            .border-t.border-gray-200.pt-4
              .text-sm.font-medium.text-gray-500.mb-2 Données
              div.bg-gray-50.p-4.rounded-lg.text-sm.overflow-auto.max-h-96
                = JSON.pretty_generate(JSON.parse(@event.data)) rescue @event.data