config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require "domain"
  devise_for :users
  mount StripeEvent::Engine, at: "/stripe-webhooks"
  get "/", to: "pages#home"

  post "/webhooks/:source", to: "webhooks#create"

  require "sidekiq/web"
  require "sidekiq-scheduler/web"
  authenticate :user, -> (user) { user.queen? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  resources :filterables, only: [], param: :model_name do
    resource :filters, only: %i[show create], controller: "filterable/filters"
    resources :views, only: %i[create], controller: "filterable/views"
    collection do
      resources :views, only: %i[destroy], as: :filterable_view, controller: "filterable/views"
    end
  end

  get "/admin", to: "admin/items#index"

  devise_scope :user do
    namespace :queen do
      authenticate :user, -> (user) { user.queen? } do
        resources :users, only: %i[index show edit update destroy new create] do
          patch :set_localhost, on: :member
        end
        resources :store_orders, only: %i[index show]
        resources :events, only: [:index, :show] do
          post :relaunch, on: :member
        end
      end
    end

    resource :profile, only: %i[edit update]

    namespace :admin do
      authenticate :user, -> (user) { user.queen? || user.admin? } do
        resource :instagram, only: [:show, :update] do
          patch :update_engagement_config, on: :member
          post :launch_engagement, on: :member
          patch :toggle_status, on: :member
        end
        get "instagram/logs", to: "instagram_logs#index", as: :instagram_logs
        resources :authors do
          delete :remove_avatar, on: :member, controller: :avatars
        end
        resource :onboarding, only: %i[new create]
        resource :subscription, only: %i[create destroy]
        resources :stores, only: %i[show edit update] do
          resources :categories, only: %i[new create edit update]
          resources :shipping_methods, only: %i[new create edit update]
          resources :specifications, only: %i[new create edit update]
        end
        resources :specifications, only: [:destroy, :index, :new, :create, :edit, :update]
        resources :categories, only: [:destroy, :index, :new, :create, :edit, :update]
        resources :shipping_methods, only: [:destroy]
        resources :collections, only: %i[index new create edit destroy update]
        resources :carousel_cards, only: %i[new create edit destroy update] do
          patch :update_position, on: :member
        end
        resource :bulk_edit_items, only: [] do
          patch :online, on: :member
          patch :offline, on: :member
          patch :add_to_collection, on: :member
        end

        resources :items, only: %i[index new create edit update destroy] do
          delete :remove_photo, on: :member, controller: :photos
          patch :archive, on: :member, controller: :archives
          patch :unarchive, on: :member, controller: :archives
          patch :add_stock, on: :member, controller: :stocks
          patch :remove_stock, on: :member, controller: :stocks
        end

        resources :orders, only: %i[index show destroy]
        resources :bookings, only: %i[index new create show edit update destroy] do
          post :add_step, on: :member
          post :reset_steps, on: :member
          post :create_message, on: :member
          post :fetch_instagram_messages, on: :member
        end
        resources :venues
        resources :booking_contacts
        resource :account, only: %i[show edit update]
      end
    end
  end

  constraints(Domain) do
    root to: "pages#home"
    get "/contact",         to: "pages#contact"
    get "/about",           to: "pages#about"
    post "/send_message",   to: "pages#send_message"
    get "/store",           to: "stores#show"
    get "/library",         to: "stores#library"
    get "/portfolio",       to: "pages#portfolio"
    get "/authors", to: "ttt/authors#index"
    get "/authors/:id", to: "ttt/authors#show", as: :author
    get "/confidentiality", to: "pages#confidentiality"

    resource :checkout, only: [:show] do
      post :confirm_payment, ons: :member
    end
    resources :items, only: [:show] do
      resource :checkout, only: [] do
        post :add, on: :member, controller: :carts
        post :remove, on: :member, controller: :carts
      end
    end
    resources :orders, only: [:show]
    resources :order_intents, only: [:create]
    resource :order_intents, only: [] do
      patch :undo_shipping_method, on: :member
      patch :undo_service_point, on: :member
      patch :shipping_method, on: :member
      patch :service_point, on: :member
    end
  end

  namespace :api do
    resources :social_campagnes, only: [] do
      member do
        get :status
        patch :status
        post :logs
      end
      resources :social_targets, only: [] do
        member do
          post :like
          patch :update
        end
      end
    end
  end
end

app/models/store.rb
# frozen_string_literal: true

class Store < ApplicationRecord
  belongs_to :admin, class_name: "User"
  has_many :categories, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :specifications, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :collections, dependent: :destroy
  has_rich_text :about
  has_one_attached :about_photo

  encrypts :postmark_key
  encrypts :sendcloud_private_key
  encrypts :sendcloud_public_key

  validates :slug, uniqueness: true
  validates :holiday_sentence, presence: true, if: :holiday?
  validates :postal_code, :city, :country, :address, :name, :domain, :slug, presence: true

  after_create :create_endi_profile

  def create_endi_profile
    # EndiServices::NewUser.new(self).call
  end

  def active_collections_with_items
    collections.includes(:items).where(items: { status: :active }).order(created_at: :desc)
  end

  def pre_sale_collections_with_items
    collections.includes(:items).where(items: { status: :pre_sale }).order(created_at: :desc)
  end

  def active_items
    items.where(status: :active).order(created_at: :desc)
  end

  def holiday?
    holiday
  end

  def active_subscription?
    stripe_subscription_id.present? && subscription_status == "active"
  end

  def full_address
    "#{address}, #{postal_code} #{city}, #{country}"
  end

  def stripe_account_completed?
    stripe_account_id.present? && details_submitted && charges_enable && payouts_enable
  end
end

app/controllers/admin/stores_controller.rb
# frozen_string_literal: true

module Admin
  class StoresController < AdminController
    def show
      @store = Current.store
      authorize! @store
      @categories = @store.categories
      @shipping_methods = []
      @specifications = @store.specifications
    end

    def edit
      @store = Current.store
      authorize! @store
    end

    def update
      @store = Store.find(params[:id])
      authorize! @store
      if @store.update(store_params)
        respond_to do |format|
          format.html { redirect_to admin_store_path(@store), notice: t(".success") }
          format.turbo_stream
        end
      else
        render :edit
      end
    end

    private

    def store_params
      params.require(:store).permit(:name, :meta_title, :meta_description, :about, :facebook_url, :instagram_url,
                                    :holiday, :holiday_sentence, :city, :postal_code, :address,
                                    :country, :about_photo)
    end
  end
end

app/controllers/stores_controller.rb
# frozen_string_literal: true

class StoresController < ApplicationController
  before_action :set_store, :set_filters

  def show
    @max_price = max_price
    @min_price = min_price
    @default_sort = default_sort
    @query = params.dig(:filters, :query)
    @items = fetch_items
    @collections = @store.active_collections_with_items

    return unless params[:filters]

    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def max_price
    params.dig(:filters, :max_price) || @store.items&.maximum(:price_cents)&.fdiv(100)
  end

  def min_price
    params.dig(:filters, :min_price) || 0.00
  end

  def default_sort
    params.dig(:filters, :sort) || "Nouveautés"
  end

  def fetch_items
    return @store.active_items unless params[:filters]

    items = @store.items.includes(:category).where(category: { name: selected_filters },
                                                   status: :active).where(price_range_inputs).order(sorting_input)
    items = items.search_by_name_and_description(@query) if @query.present? && @query != ""
    items
  end

  def sorting_input
    case params.dig(:filters, :sort)
    when "Prix croissant"
      "items.price_cents ASC"
    when "Prix décroissant"
      "items.price_cents DESC"
    when "A-Z"
      "items.name ASC"
    else
      "items.created_at DESC"
    end
  end

  def price_range_inputs
    min_price_cents = params.dig(:filters, :min_price).gsub(",", ".").to_f * 100
    max_price_cents = params.dig(:filters, :max_price).gsub(",", ".").to_f * 100
    "items.price_cents >= #{min_price_cents} AND items.price_cents <= #{max_price_cents}"
  end

  def set_filters
    session[:filters] = if params[:filters]
                          params.require(:filters).permit(@store.categories.pluck(:name)).transform_values(&:to_i)
                        else
                          @store.categories.pluck(:name).index_with { |_name| 1 }
                        end
  end

  def set_store
    @store = Current.store
  end

  def selected_filters
    session[:filters].select { |_k, v| v == 1 }.keys
  end
end

app/views/stores/_card.html.slim
= link_to item_path(item), class:"relative" do
  .group.relative.flex.flex-col.overflow-hidden.rounded-lg.border.shadow-sm class="hover:shadow-lg hover:scale-[1.005] transition-all  #{'disabled' if item.soldout?}" data-card-animate-target="card"
    .aspect-h-4.aspect-w-3.bg-form-input.transition.sm:aspect-none.sm:h-96
      - if item.photos.attached?
        = image_tag item.photos.first.variant(resize_to_fill: [600, 600]), class: "h-full w-full object-cover object-center sm:h-full sm:w-full"
    .flex.flex-1.flex-col.space-y-2.p-4.bg-form-input.min-h-36
      h3.text-sm.font-medium.text-contrast
        span.absolute.inset-0[aria-hidden="true"]
        = item.name
      p.text-sm.text-content.line-clamp-3
        = item.description
      p.text-base.font-medium.text-contrast class="!mt-auto"
        = "#{item.price} €"
      - if item.stock == 1
        p.text-sm.font-base.text-contrast.text-red-500
          = "Plus qu'un seul exemplaire en stock !"

  - if item.soldout?
    .absolute.left-1/2.top-1/2.-translate-x-1/2.-translate-y-1/2.text-center.opacity-100
      .text-3xl.text-red-500.font-bold RUPTURE DE STOCK

app/views/stores/_collection.html.slim
- store = collection.items.first.store

- if File.exist?(Rails.root.join('app', 'views', "#{store.slug}", 'shared', '_card.html.slim'))
  = render "#{store.slug}/shared/card", item: collection.items.first
- else
  = link_to item_path(collection.items.first), class:"relative" do
  .group.relative.flex.flex-col.overflow-hidden.rounded-lg.border.shadow-sm class="hover:shadow-lg hover:scale-[1.005] transition-all  #{'disabled' if collection.soldout?}"
    .aspect-h-4.aspect-w-3.bg-contrast.sm:aspect-none.sm:h-96
      = image_tag collection.cover_image, class: "h-full w-full object-cover object-center sm:h-full sm:w-full"

    .flex.flex-1.flex-col.space-y-2.p-4.bg-contour.min-h-36
      h3.text-sm.font-medium.text-contrast
        span.absolute.inset-0[aria-hidden="true"]
        = collection.name
      p.text-sm.text-content
        = collection.items.first.description
      p.text-base.font-medium.text-contrast class="!mt-auto"
        = t(".price_range", min: number_to_currency(collection.min_item_price), max: number_to_currency(collection.max_item_price))
      - if collection.stock == 1
        p.text-sm.font-base.text-contrast.text-red-500
          = "Plus qu'un seul exemplaire en stock !"

  - if collection.items.first.soldout?
    .absolute.left-1/2.top-1/2.-translate-x-1/2.-translate-y-1/2.text-center.opacity-100
      .text-3xl.text-red-500.font-bold RUPTURE DE STOCK

app/views/stores/_filters.html.slim
aside
  h2.sr-only
    | Filters
  .hidden.lg:block
    .space-y-10.divide-y.divide-content

      div
        legend.block.text-sm.font-medium.text-contrast
          | Filtres
        .space-y-3.pt-6 data-controller="autosave"
          = simple_form_for :filters, url: store_path, method: :get, html: {data: { turbo_stream: true,  controller: "autosave"}} do |f|
            = f.input :query, label: "Recherche", input_html: { value: @query, data: { action: "keyup->autosave#submit" }}
            = f.input :sort, collection: ["Prix croissant", "Prix décroissant", "A-Z", "Nouveautés"], label: false, input_html: {data: { action: "change->autosave#submit" }, id: "sort", class: " rounded border-content text-primary focus:ring-primary"}, wrapper_html: { class: "pb-3 mb-0 flex items-center"}, selected: @default_sort
            - unless Current.store.slug == "ttt"
              p.text-sm.text-midgray
                | Prix
              .flex.gap-3
                .relative.w-full
                  = f.input :min_price, label: false, input_html: { value: number_with_precision(@min_price, precision: 2), data: { action: "change->autosave#submit" }}
                  span.text-midgray.text-xs.absolute.right-3.top-3
                    | €
                .relative.w-full
                  = f.input :max_price, label: false, input_html: { value: number_with_precision(@max_price, precision: 2), data: { action: "change->autosave#submit" }}
                  span.text-midgray.text-xs.absolute.right-3.top-3
                    | €


            - Current.store.categories.each_with_index do |category, index|
              .flex.items-center
                = f.input category.name, as: :boolean, boolean_style: :nested, label: t(category.name), input_html: {data: { action: "change->autosave#submit" },checked: session[:filters][category.name].to_i.positive?, id: "category-#{index}", class: "h-6 w-4 checked:!bg-primary rounded border-content text-primary focus:ring-primary"}, wrapper_html: { class: "pb-3 mb-0 flex items-center"}, label_html: {class: 'top-1 left-6 text-sm text-midgray'}

            - unless params[:library]
              = link_to store_path(library: true) do
                .bg-center.bg-cover.bg-no-repeat.bg-center.h-12.w-full.flex.items-center.justify-end.text-light.text-sm.font-bold[
                  style="background-image: url(#{asset_path('ttt/green_dot_fade.png')})"
                  class="transition-all duration-300 cursor-pointer hover:-translate-x-10"]
                    span.pr-3 Acces Librairie

app/views/stores/_item.html.slim
- if File.exist?(Rails.root.join('app', 'views', "#{store.slug}", 'shared', '_card.html.slim'))
  = render "#{store.slug}/shared/card", item: item
- else
  = render "stores/card", item: item

app/views/stores/_items.html.slim
#store-items.grid.grid-cols-1.gap-8.h-full.sm:grid-cols-2.sm:gap-x-12.sm:gap-y-16.lg:gap-x-16.xl:grid-cols-3 data-controller="card-animate"
  - collections.each do |collection|
    = render "stores/collection", collection: collection

  - items.each do |item|
    - unless item.collection.present?
      = render "stores/item", item: item, store: @store

app/views/stores/_mobile_filters.html.slim
.fixed.inset-0.z-40.flex
  .relative.ml-auto.flex.h-full.w-full.max-w-xs.flex-col.overflow-y-auto.bg-contrast.py-4.pb-6.shadow-xl
    .flex.items-center.justify-between.px-4
      h2.text-lg.font-medium.text-contrast
        | Filters
      button.relative.-mr-2.flex.h-10.w-10.items-center.justify-center.p-2.text-midgray.hover:text-midgray[type="button"]
        span.absolute.-inset-0.5
        span.sr-only
          | Close menu
        svg.h-6.w-6[fill="none" viewbox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true"]
          path[stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"]
    form.mt-4
      .border-t.border-content.pb-4.pt-4
        fieldset
          legend.w-full.px-2
            button.flex.w-full.items-center.justify-between.p-2.text-midgray.hover:text-midgray[type="button" aria-controls="filter-section-0" aria-expanded="false"]
              span.text-sm.font-medium.text-contrast
                | Color
              span.ml-6.flex.h-7.items-center
                svg.rotate-0.h-5.w-5.transform[viewbox="0 0 20 20" fill="currentColor" aria-hidden="true"]
                  path[fill-rule="evenodd" d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z" clip-rule="evenodd"]
          #filter-section-0.px-4.pb-2.pt-4
            .space-y-6
              .flex.items-center
                input#color-0-mobile.h-4.w-4.rounded.border-content.text-primary.focus:ring-primary[name="color[]" value="white" type="checkbox"]
                label.ml-3.text-sm.text-midgray[for="color-0-mobile"]
                  | White
              .flex.items-center
                input#color-1-mobile.h-4.w-4.rounded.border-content.text-primary.focus:ring-primary[name="color[]" value="beige" type="checkbox"]
                label.ml-3.text-sm.text-midgray[for="color-1-mobile"]
                  | Beige
              .flex.items-center
                input#color-2-mobile.h-4.w-4.rounded.border-content.text-primary.focus:ring-primary[name="color[]" value="blue" type="checkbox"]
                label.ml-3.text-sm.text-midgray[for="color-2-mobile"]
                  | Blue
              .flex.items-center
                input#color-3-mobile.h-4.w-4.rounded.border-content.text-primary.focus:ring-primary[name="color[]" value="brown" type="checkbox"]
                label.ml-3.text-sm.text-midgray[for="color-3-mobile"]
                  | Brown
              .flex.items-center
                input#color-4-mobile.h-4.w-4.rounded.border-content.text-primary.focus:ring-primary[name="color[]" value="green" type="checkbox"]
                label.ml-3.text-sm.text-midgray[for="color-4-mobile"]
                  | Green
              .flex.items-center
                input#color-5-mobile.h-4.w-4.rounded.border-content.text-primary.focus:ring-primary[name="color[]" value="purple" type="checkbox"]
                label.ml-3.text-sm.text-midgray[for="color-5-mobile"]
                  | Purple
      .border-t.border-content.pb-4.pt-4
        fieldset
          legend.w-full.px-2
            button.flex.w-full.items-center.justify-between.p-2.text-midgray.hover:text-midgray[type="button" aria-controls="filter-section-1" aria-expanded="false"]
              span.text-sm.font-medium.text-contrast
                | Category
              span.ml-6.flex.h-7.items-center
                svg.rotate-0.h-5.w-5.transform[viewbox="0 0 20 20" fill="currentColor" aria-hidden="true"]
                  path[fill-rule="evenodd" d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z" clip-rule="evenodd"]
          #filter-section-1.px-4.pb-2.pt-4
            .space-y-6
              .flex.items-center
                input#category-0-mobile.h-4.w-4.rounded.border-content.text-primary.focus:ring-primary[name="category[]" value="new-arrivals" type="checkbox"]
                label.ml-3.text-sm.text-midgray[for="category-0-mobile"]
                  | All New Arrivals
              .flex.items-center
                input#category-1-mobile.h-4.w-4.rounded.border-content.text-primary.focus:ring-primary[name="category[]" value="tees" type="checkbox"]
                label.ml-3.text-sm.text-midgray[for="category-1-mobile"]
                  | Tees
              .flex.items-center
                input#category-2-mobile.h-4.w-4.rounded.border-content.text-primary.focus:ring-primary[name="category[]" value="crewnecks" type="checkbox"]
                label.ml-3.text-sm.text-midgray[for="category-2-mobile"]
                  | Crewnecks
              .flex.items-center
                input#category-3-mobile.h-4.w-4.rounded.border-content.text-primary.focus:ring-primary[name="category[]" value="sweatshirts" type="checkbox"]
                label.ml-3.text-sm.text-midgray[for="category-3-mobile"]
                  | Sweatshirts
              .flex.items-center
                input#category-4-mobile.h-4.w-4.rounded.border-content.text-primary.focus:ring-primary[name="category[]" value="pants-shorts" type="checkbox"]
                label.ml-3.text-sm.text-midgray[for="category-4-mobile"]
                  | Pants & Shorts
      .border-t.border-content.pb-4.pt-4
        fieldset
          legend.w-full.px-2
            button.flex.w-full.items-center.justify-between.p-2.text-midgray.hover:text-midgray[type="button" aria-controls="filter-section-2" aria-expanded="false"]
              span.text-sm.font-medium.text-contrast
                | Sizes
              span.ml-6.flex.h-7.items-center
                svg.rotate-0.h-5.w-5.transform[viewbox="0 0 20 20" fill="currentColor" aria-hidden="true"]
                  path[fill-rule="evenodd" d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z" clip-rule="evenodd"]
          #filter-section-2.px-4.pb-2.pt-4
            .space-y-6
              .flex.items-center
                input#sizes-0-mobile.h-4.w-4.rounded.border-content.text-primary.focus:ring-primary[name="sizes[]" value="xs" type="checkbox"]
                label.ml-3.text-sm.text-midgray[for="sizes-0-mobile"]
                  | XS
              .flex.items-center
                input#sizes-1-mobile.h-4.w-4.rounded.border-content.text-primary.focus:ring-primary[name="sizes[]" value="s" type="checkbox"]
                label.ml-3.text-sm.text-midgray[for="sizes-1-mobile"]
                  | S
              .flex.items-center
                input#sizes-2-mobile.h-4.w-4.rounded.border-content.text-primary.focus:ring-primary[name="sizes[]" value="m" type="checkbox"]
                label.ml-3.text-sm.text-midgray[for="sizes-2-mobile"]
                  | M
              .flex.items-center
                input#sizes-3-mobile.h-4.w-4.rounded.border-content.text-primary.focus:ring-primary[name="sizes[]" value="l" type="checkbox"]
                label.ml-3.text-sm.text-midgray[for="sizes-3-mobile"]
                  | L
              .flex.items-center
                input#sizes-4-mobile.h-4.w-4.rounded.border-content.text-primary.focus:ring-primary[name="sizes[]" value="xl" type="checkbox"]
                label.ml-3.text-sm.text-midgray[for="sizes-4-mobile"]
                  | XL
              .flex.items-center
                input#sizes-5-mobile.h-4.w-4.rounded.border-content.text-primary.focus:ring-primary[name="sizes[]" value="2xl" type="checkbox"]
                label.ml-3.text-sm.text-midgray[for="sizes-5-mobile"]
                  | 2XL

app/views/stores/library.html.slim
.bg-light.w-full.min-h-screen.pt-36.ttt-dark
  .max-w-5xl.mx-auto
    h1.text-4xl.text-contrast Libraire, commander nos BD avec des prix professionels
    p.text-contrast.mt-4
      | Les avantages libraire sont les prix professionels, la contrepartie est que nous demandons une commande pour 5 ouvrages minimum

  - filters = Current.store.filters
  .md:pt-24 class="min-h-[calc(100vh-10rem)]"
    main.mx-auto.max-w-2xl.px-4.lg:max-w-7xl.lg:px-8
      .pb-24.pt-12.lg:grid.lg:grid-cols-3.lg:gap-x-8.xl:grid-cols-4 class="#{'xl:!grid-cols-3' unless filters}"
        - if filters
          = render "filters"
        section.mt-6.lg:col-span-2.lg:mt-0.xl:col-span-3[aria-labelledby="product-heading"]
          - if @items.blank?
            .flex.items-center.justify-center.py-24
              h1.text-4xl.text-midgray Aucune résultat pour votre recherche
          - elsif Current.store.holiday?
            .flex.items-center.justify-center.py-24
              h1.text-4xl.text-midgray = Current.store.holiday_sentence
          - else
            h2#product-heading.sr-only
              | Products
            = render "items", items: @items, collections: @collections

app/views/stores/show.html.slim
style
  | .bg-light {
  |   background-color: #{'#F7FFF5 !important' if params[:library]};
  | }
  | .text-primary {
  |   color: #{'#71D1AF !important' if params[:library]};
  | }


- filters = Current.store.filters
.bg-light.md:pt-24 class="min-h-[calc(100vh-10rem)]"
  main.mx-auto.max-w-2xl.px-4.lg:max-w-7xl.lg:px-8
    .
      - if params[:library]
        .bg-center.bg-cover.bg-no-repeat.bg-center.h-12.w-1/4.flex.items-center.justify-end.text-light.text-sm.font-bold.mb-6[
          style="background-image: url(#{asset_path('ttt/green_dot_fade.png')})"]
          span.pr-3 Espace Librairie
        .text-primary.bg-white.bg-opacity-80.rounded-xl.shadow-md.p-6.mb-8
          h2.text-xl.font-bold.mb-2 Cette zone du site est réservée aux libraires

          p.mb-4.text-content
            | Retrouvez ici toutes les informations utiles pour les professionnels du livre.

          .mb-4
            h3.font-semibold.mb-1 Tarifs dégressifs :
            ul.list-disc.list-inside.text-content
              li 1 livre = 0 %
              li 2 livres = 10 %
              li 3 livres = 20 %
              li 4 livres = 30 %
              li 5 livres ou plus = 40 %

          .mb-4
            h3.font-semibold.mb-1 Facturation :
            p.text-content
              | Une facture vous sera envoyée par mail au moment de la commande.

          .mb-4
            h3.font-semibold.mb-1 Besoin d’informations ?
            p.text-content
              | Contactez-nous à
              a.text-contrast.font-semibold.ml-1 href="mailto:turbotimetravel@gmail.com" turbotimetravel@gmail.com

          .mb-2
            h3.font-semibold.mb-1 Paiement différé :
            p.text-content
              | Si vous souhaitez payer en fin de mois ou par virement, contactez-nous par mail. Nous traiterons votre demande dans les plus brefs délais.

    .pb-24.pt-12.lg:grid.lg:grid-cols-3.lg:gap-x-8.xl:grid-cols-4 class="#{'xl:!grid-cols-3' unless filters} min-h-[calc(100vh-10rem)]"
      - if filters
        = render "filters"
      section.mt-6.lg:col-span-2.lg:mt-0.xl:col-span-3[aria-labelledby="product-heading"]
        - if Current.store.holiday?
          .flex.items-center.justify-center.py-24
            h1.text-4xl.text-midgray = Current.store.holiday_sentence
        - elsif @items.blank?
          .flex.items-center.justify-center.py-24
            h1.text-4xl.text-midgray Aucune résultat pour votre recherche
        - else
          h2#product-heading.sr-only
            | Products
          = render "items", items: @items, collections: @collections

app/views/stores/show.turbo_stream.slim
= turbo_stream.replace "store-items", partial: "items", locals: { items: @items, collections: @collections }