config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require "domain"
  devise_for :users
  mount StripeEvent::Engine, at: "/stripe-webhooks"
  get "/", to: "pages#home"

  post "/webhooks/:source", to: "webhooks#create"

  require "sidekiq/web"
  require "sidekiq-scheduler/web"
  authenticate :user, -> (user) { user.queen? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  resources :filterables, only: [], param: :model_name do
    resource :filters, only: %i[show create], controller: "filterable/filters"
    resources :views, only: %i[create], controller: "filterable/views"
    collection do
      resources :views, only: %i[destroy], as: :filterable_view, controller: "filterable/views"
    end
  end

  get "/admin", to: "admin/items#index"

  devise_scope :user do
    namespace :queen do
      authenticate :user, -> (user) { user.queen? } do
        resources :users, only: %i[index show edit update destroy new create] do
          patch :set_localhost, on: :member
        end
        resources :store_orders, only: %i[index show]
        resources :events, only: [:index, :show] do
          post :relaunch, on: :member
        end
      end
    end

    resource :profile, only: %i[edit update]

    namespace :admin do
      authenticate :user, -> (user) { user.queen? || user.admin? } do
        resource :instagram, only: [:show, :update] do
          patch :update_engagement_config, on: :member
          post :launch_engagement, on: :member
          patch :toggle_status, on: :member
        end
        get "instagram/logs", to: "instagram_logs#index", as: :instagram_logs
        resources :authors do
          delete :remove_avatar, on: :member, controller: :avatars
        end
        resource :onboarding, only: %i[new create]
        resource :subscription, only: %i[create destroy]
        resources :stores, only: %i[show edit update] do
          resources :categories, only: %i[new create edit update]
          resources :shipping_methods, only: %i[new create edit update]
          resources :specifications, only: %i[new create edit update]
        end
        resources :specifications, only: [:destroy, :index, :new, :create, :edit, :update]
        resources :categories, only: [:destroy, :index, :new, :create, :edit, :update]
        resources :shipping_methods, only: [:destroy]
        resources :collections, only: %i[index new create edit destroy update]
        resources :carousel_cards, only: %i[new create edit destroy update] do
          patch :update_position, on: :member
        end
        resource :bulk_edit_items, only: [] do
          patch :online, on: :member
          patch :offline, on: :member
          patch :add_to_collection, on: :member
        end

        resources :items, only: %i[index new create edit update destroy] do
          delete :remove_photo, on: :member, controller: :photos
          patch :archive, on: :member, controller: :archives
          patch :unarchive, on: :member, controller: :archives
          patch :add_stock, on: :member, controller: :stocks
          patch :remove_stock, on: :member, controller: :stocks
        end

        resources :orders, only: %i[index show destroy]
        resources :bookings, only: %i[index new create show edit update destroy] do
          post :add_step, on: :member
          post :reset_steps, on: :member
          post :create_message, on: :member
          post :fetch_instagram_messages, on: :member
        end
        resources :venues
        resources :booking_contacts
        resource :account, only: %i[show edit update]
      end
    end
  end

  constraints(Domain) do
    root to: "pages#home"
    get "/contact",         to: "pages#contact"
    get "/about",           to: "pages#about"
    post "/send_message",   to: "pages#send_message"
    get "/store",           to: "stores#show"
    get "/library",         to: "stores#library"
    get "/portfolio",       to: "pages#portfolio"
    get "/authors", to: "ttt/authors#index"
    get "/authors/:id", to: "ttt/authors#show", as: :author
    get "/confidentiality", to: "pages#confidentiality"

    resource :checkout, only: [:show] do
      post :confirm_payment, ons: :member
    end
    resources :items, only: [:show] do
      resource :checkout, only: [] do
        post :add, on: :member, controller: :carts
        post :remove, on: :member, controller: :carts
      end
    end
    resources :orders, only: [:show]
    resources :order_intents, only: [:create]
    resource :order_intents, only: [] do
      patch :undo_shipping_method, on: :member
      patch :undo_service_point, on: :member
      patch :shipping_method, on: :member
      patch :service_point, on: :member
    end
  end

  namespace :api do
    resources :social_campagnes, only: [] do
      member do
        get :status
        patch :status
        post :logs
      end
      resources :social_targets, only: [] do
        member do
          post :like
          patch :update
        end
      end
    end
  end
end

app/models/order.rb
# frozen_string_literal: true

# app/models/item.rb
class Order < ApplicationRecord
  extend Enumerize
  include Presentable
  include PgSearch::Model

  delegate :address, to: :shipping, prefix: true, allow_nil: true

  belongs_to :user
  belongs_to :store
  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items
  has_one_attached :label
  has_one :shipping, dependent: :destroy
  has_one :fee, dependent: :destroy
  has_one :discount, dependent: :destroy

  monetize :amount_cents

  pg_search_scope :search_by_client,
                  associated_against: {
                    user: %i[first_name last_name email],
                    shipping: %i[address_first_line address_second_line postal_code city country]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }

  STATUSES = %w[pending confirmed paid canceled refunded sent].freeze

  enumerize :status, in: STATUSES, default: "pending", predicates: true

  validates :amount, presence: true
  validates :status, presence: true

  def total_price
    if shipping&.api_shipping_id.present?
      amount + shipping.cost + fee.amount - (discount&.amount || 0)
    else
      amount - (discount&.amount || 0)
    end
  end

  def total_price_cents
    if shipping&.api_shipping_id.present?
      amount_cents + shipping.cost_cents + fee.amount_cents - (discount&.amount_cents || 0)
    else
      amount_cents - (discount&.amount_cents || 0)
    end
  end

  # Le discount n'est pas inclus dans le prix logistique, il s'applique sur le total
  def logistic_and_shipping_price
    shipping.cost + fee.amount
  end

  def full_address
    "#{shipping.address}, #{shipping.postal_code} #{shipping.city}, #{shipping.country}"
  end
end

app/controllers/admin/orders_controller.rb
# frozen_string_literal: true

module Admin
  class OrdersController < AdminController
    before_action :set_order, only: %i[show destroy]

    def index
      @orders = authorized_scope(Order.all)
      @orders = @orders.search_by_client(params[:search]) if params[:search].present?

      authorize! @orders
    end

    def show; end

    def destroy
      if !@order.paid? && @order.destroy
        redirect_to admin_orders_path, status: :see_other, notice: t(".success")
      else
        flash.now[:notice] = t(".error")
        render :show, status: :unprocessable_entity
      end
    end

    private

    def set_order
      @order = Order.find(params[:id])
      authorize! @order, with: Admin::OrderPolicy
    end
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @items = Checkout.new(@order.items.pluck(:id)).cart
    return unless @order.paid?

    # session.clear
    session[:checkout_items] = []
  end
end

app/views/admin/orders/_form.html.slim
= simple_form_for [:admin, @order] do |field|
  = field.input :status, collection: Order::STATUSES.map {|status| [t(status), status]}, label: "Statut"
  = field.button :submit, "Enregistrer", class: "btn btn-primary"

app/views/admin/orders/_order.html.slim
= turbo_frame_tag dom_id(order), class: "table-row text-sm text-contrast"
  .table-cell
    = order.id
  .table-cell
    = l(order.created_at, format: :short)
  .table-cell.max-w-28.cursor-help title=order.user.full_name
    = order.user.full_name
  .table-cell.max-w-36.cursor-help title=order.user.email
    = order.user.email
  .table-cell.max-w-36.cursor-help title=order.shipping.full_address
    = order.shipping.full_address
  .table-cell
    = number_to_currency(order.amount, format: "%n €")
  .table-cell
    = order.status
  .table-cell
    = order.shipping.status
  .table-cell
    = render List::Component.new(item: order, links:[{icon: "fas fa-eye", label: "Voir", path: admin_order_path(order), options: { data: { turbo: false }}}])

app/views/admin/orders/_orders.html.slim
= turbo_frame_tag :orders, class: "table-row-group w-full relative" do

  = render EmptyFolder::Component.new(title: t("orders.empty_folder.title"), subtitle: t("orders.empty_folder.subtitle"))

  - orders.order(id: :desc).each do |order|
    = render "admin/orders/order", order: order

app/views/admin/orders/edit.html.slim
= render TurboModal::Component.new(title: "Modifier la commande n° #{@order.id}")
  = render "form"

app/views/admin/orders/index.html.slim
= render Header::Component.new do |header|
  / - header.with_tabs do
  /   = render Tabs::Component.new(tabs: [{name: "Articles", path: admin_items_path},
  /                                       {name: "Collections", path: admin_collections_path},
  /                                       {name: "Catégories", path: admin_categories_path},
  /                                       {name: "Spécifications", path: admin_specifications_path}])
  / - header.with_action_link do
  /   = link_to new_admin_item_path do
  /     = render Buttons::Option::Component.new(label: "Ajouter un article", icon: "fa-solid fa-plus")
  .px-4.sm:px-6.lg:px-0
    .sm:flex.sm:items-center.mb-6
      .sm:flex-auto
        h1.text-base.font-semibold.leading-6.text-contrast
          | Commandes
        p.mt-2.text-sm.text-midgray
          | Liste de toutes les commandes de votre boutique.
    .mt-8.flow-root
      = form_tag admin_orders_path, method: :get, class: "mt-6"
        .flex.flex-row.items-center
          .flex-auto
            = text_field_tag :search, params[:search],
                              placeholder: "Rechercher une commande, adresse, client, mail, etc.",
                              class: "form-input placeholder:text-content"



      .-mx-4.-my-2.overflow-x-auto.sm:-mx-6.lg:-mx-8
        .inline-block.min-w-full.py-2.align-middle.sm:px-6.lg:px-8

          .table.w-full.pb-36.mt-6
            .table-header-group
              .table-row
                .table-cell
                  | Ref.
                .table-cell
                  | Date
                .table-cell
                  | Client
                .table-cell
                  | Mail
                .table-cell
                  | Adresse
                .table-cell
                  | Prix
                .table-cell
                  | Statut
                .table-cell
                  | Livraison
                .table-cell.w-8
                  span.sr-only
                    | Actions


            = render "admin/orders/orders", orders: @orders
            - header.with_pagination do
              / == pagy_nav(@pagy)

app/views/admin/orders/show.html.slim
.bg-light.min-h-screen.py-12.md:pt-0
  .mx-auto.max-w-5xl.px-6.md:px-0
    .bg-light.py-10
      .px-4.sm:px-6.lg:px-0
        .flex.w-full.justify-between
          .flex
            = button_to admin_order_path(@order), method: :delete, data: { turbo: false } do
              i#delete-order.fa-solid.fa-trash.text-xl.mr-3
            h1.text-base.font-semibold.leading-6.text-contrast
              = t('orders.show.order_details')
          .mt-4.sm:mt-0.sm:flex-none
            - if @order.label.attached?
              = link_to @order.label, target: "_blank" do
                i.fa-solid.fa-sheet-plastic.text-xl
              = link_to @order.shipping.api_tracking_url, target: "_blank" do
                i.fa-solid.fa-truck.text-xl.ml-3
            - else
              i.fa-solid.fa-sheet-plastic.text-xl.text-gray-300


    section.mt-10.border-t.border-content[aria-labelledby="order-heading"]
      h2#order-heading.sr-only = t('orders.show.your_order')

      h3.sr-only = t('orders.show.items')
      - Checkout.new(@order).cart.each do |item|
        = render "orders/card", item: item

      .
        h3.sr-only = t('orders.show.your_information')
        h4.sr-only = t('orders.show.addresses')
        dl.grid.grid-cols-2.gap-x-6.py-10.text-sm
          div
            dt.font-medium.text-contrast = t('orders.show.shipping_address')
            dd.mt-2.text-contrast
              address.not-italic
                span.block = @order.shipping&.full_address
          div
            dt.font-medium.text-contrast = t('orders.show.tracking_number')
            dd.mt-2.text-contrast
              address.not-italic
                = link_to @order.shipping&.api_tracking_url, target: "_blank" do
                  span.block.hover:text-primary = @order.shipping&.api_tracking_number

        h4.sr-only = t('orders.show.payment')
        dl.grid.grid-cols-2.gap-x-6.border-t.border-content.py-10.text-sm
          div
            dt.font-medium.text-contrast = t('orders.show.payment_method')
            dd.mt-2.text-contrast
              p Stripe

          div
            dt.font-medium.text-contrast = t('orders.show.shipping_method')
            dd.mt-2.text-contrast
              p = t(@order.shipping&.method_carrier)
              p.text-content.text-xs = @order.shipping&.api_method_name

        h3.sr-only = t('orders.show.summary')
        dl.space-y-6.border-t.border-content.pt-10.text-sm
          .flex.justify-between
            dt.font-medium.text-contrast = t('orders.show.subtotal')
            dd.text-contrast = number_to_currency(@order.amount, format: "%n €")
          .flex.justify-between
            dt.font-medium.text-contrast = t('orders.show.shipping')
            dd.text-contrast = number_to_currency(@order.shipping&.cost, format: "%n €")
          .flex.justify-between
            dt.font-medium.text-contrast = t('orders.show.logistic')
            dd.text-contrast = number_to_currency(@order.fee&.amount, format: "%n €")
          .flex.justify-between.border-t.border-content/50.pt-6.text-base.font-medium
            dt.font-medium.text-contrast = t('orders.show.total')
            dd.text-contrast = number_to_currency(@order.total_price, format: "%n €")

app/views/admin/orders/update.turbo_stream.slim
= turbo_stream.replace dom_id(@order), partial: "admin/orders/order", locals: { order: @order }